#!/usr/bin/env python3
import argparse
import os
import sys

# =============================================================================
# Templates
# =============================================================================

HEADER_TEMPLATE = """#!/bin/bash
set -e

# Generated by github.com/jsperger/jules-r-tex-setup/generate_setup_scripts.py
# Target Distro: {distro_codename}
"""

# R Installation Template
# Uses r2u for fast binary installations on Ubuntu.
# Supports dynamic distro codename.
R_INSTALL_TEMPLATE = """

# ========================= R installation =========================
# Installing R using r2u (https://github.com/eddelbuettel/r2u)
# Target script: add_cranapt_{distro_codename}.sh
echo "Installing R for {distro_codename}..."
curl -f https://raw.githubusercontent.com/eddelbuettel/r2u/refs/heads/master/inst/scripts/add_cranapt_{distro_codename}.sh | sudo bash
"""

# R Package Installation (via apt-get for r2u)
R_PACKAGES_TEMPLATE = """

# ========================= R Packages =========================
# Installing requested R packages via apt (r2u binaries)
echo "Installing R packages..."
sudo apt update
sudo apt install -y {packages}
"""

# Air Installation (Posit Air)
AIR_INSTALL_TEMPLATE = """

# ======================= Air installation =========================
echo "Installing Posit Air..."
curl -LsSf https://github.com/posit-dev/air/releases/latest/download/air-installer.sh | sudo AIR_INSTALL_DIR=/usr/local/bin sh
"""

# Quarto: Latest Stable
QUARTO_LATEST_TEMPLATE = """

# ======================= Quarto installation (Latest Stable) ======================
REPO="quarto-dev/quarto-cli"
ARCH_PATTERN="linux-amd64.deb"

echo "Finding latest stable Quarto release..."
# The /releases/latest endpoint specifically excludes pre-releases
DOWNLOAD_URL=$(curl -s "https://api.github.com/repos/$REPO/releases/latest" | \
    jq -r '.assets[] | select(.name | endswith("'"$ARCH_PATTERN"'")) | .browser_download_url')

if [ -z "$DOWNLOAD_URL" ] || [ "$DOWNLOAD_URL" == "null" ]; then
    echo "Error: Could not find the stable .deb asset for $ARCH_PATTERN."
    exit 1
fi

FILE_NAME=$(basename "$DOWNLOAD_URL")
echo "Downloading $FILE_NAME..."
curl -L -o "/tmp/$FILE_NAME" "$DOWNLOAD_URL"

echo "Installing Quarto..."
sudo apt update
sudo apt install -y "/tmp/$FILE_NAME"
rm "/tmp/$FILE_NAME"
"""

# Quarto: Prerelease
QUARTO_PRERELEASE_TEMPLATE = """

# ======================= Quarto installation (Prerelease) ======================
REPO="quarto-dev/quarto-cli"
ARCH_PATTERN="linux-amd64.deb"

echo "Finding latest Quarto prerelease..."
# Fetch releases list and take the first one (which is the absolute latest, usually prerelease)
DOWNLOAD_URL=$(curl -s https://api.github.com/repos/$REPO/releases | \
    jq -r '.[0].assets[] | select(.name | endswith("'"$ARCH_PATTERN"'")) | .browser_download_url')

if [ -z "$DOWNLOAD_URL" ] || [ "$DOWNLOAD_URL" == "null" ]; then
    echo "Error: Could not find the latest .deb asset for $ARCH_PATTERN."
    exit 1
fi

FILE_NAME=$(basename "$DOWNLOAD_URL")
echo "Downloading $FILE_NAME..."
curl -L -o "/tmp/$FILE_NAME" "$DOWNLOAD_URL"

echo "Installing Quarto..."
sudo apt update
sudo apt install -y "/tmp/$FILE_NAME"
rm "/tmp/$FILE_NAME"
"""

# TeX: Apt Native (TeX Live)
TEX_APT_TEMPLATE = """

# ========================= TeX installation (Apt) =========================
echo "Installing TeX Live packages: {packages}..."
sudo apt update
sudo apt install -y {packages}
"""

# TeX: TinyTeX
TEX_TINYTEX_TEMPLATE = """

# ========================= TeX installation (TinyTeX) =========================
echo "Installing TinyTeX..."
wget -qO- "https://yihui.org/tinytex/install-bin-unix.sh" | sh
"""

FOOTER_TEMPLATE = """

# ========================= Verification =========================
echo "Verifying installation..."
{verifications}
echo "Setup complete!"
"""

# =============================================================================
# Generator Logic
# =============================================================================

def generate_script_content(config):
    """
    Generates the bash script content based on the provided configuration.
    
    config: dict containing keys:
        - distro_codename: str (e.g., "noble", "jammy")
        - r: bool (install R)
        - r_packages: list[str] (optional, apt packages like 'r-cran-tidyverse')
        - air: bool (install Posit Air)
        - quarto: str ("no", "latest", "prerelease")
        - tex: str ("no", "tinytex", "apt")
        - tex_packages: list[str] (required if tex="apt")
    """
    distro = config.get("distro_codename", "noble")
    content = [HEADER_TEMPLATE.format(distro_codename=distro)]
    verifications = []

    # 1. R Installation
    if config.get("r", False):
        content.append(R_INSTALL_TEMPLATE.format(distro_codename=distro))
        verifications.append("R --version")
        
        # R Packages
        r_pkgs = config.get("r_packages", [])
        if r_pkgs:
            pkg_str = " ".join(r_pkgs)
            content.append(R_PACKAGES_TEMPLATE.format(packages=pkg_str))

    # 2. Air Installation
    if config.get("air", False):
        content.append(AIR_INSTALL_TEMPLATE)
        verifications.append("air --version")

    # 3. Quarto Installation
    q_mode = config.get("quarto", "no")
    if q_mode == "latest":
        content.append(QUARTO_LATEST_TEMPLATE)
        verifications.append("quarto --version")
    elif q_mode == "prerelease":
        content.append(QUARTO_PRERELEASE_TEMPLATE)
        verifications.append("quarto --version")

    # 4. TeX Installation
    t_mode = config.get("tex", "no")
    if t_mode == "tinytex":
        content.append(TEX_TINYTEX_TEMPLATE)
        # TinyTeX isn't always in path immediately without sourcing, but we can try basic check
        # often installed to ~/.TinyTeX/bin/...
        verifications.append("# Note: TinyTeX installed. Ensure it is in your PATH.")
    elif t_mode == "apt":
        pkgs = config.get("tex_packages", [])
        if pkgs:
            pkg_str = " ".join(pkgs)
            content.append(TEX_APT_TEMPLATE.format(packages=pkg_str))
        else:
            content.append("# Warning: TeX (Apt) requested but no packages specified.")

    # Footer
    verification_str = "\n".join(verifications)
    content.append(FOOTER_TEMPLATE.format(verifications=verification_str))

    return "\n".join(content)

def main():
    parser = argparse.ArgumentParser(description="Generate R/Quarto/TeX setup scripts.")
    parser.add_argument("--output-dir", default=".", help="Directory to save generated scripts")
    parser.add_argument("--distro", default="noble", help="Ubuntu codename (e.g., noble, jammy, plucky)")
    args = parser.parse_args()

    # Define standard configurations matching the project
    configs = [
        {
            "filename": "setup_quarto_latest.sh",
            "config": {
                "r": False,
                "quarto": "latest",
                "tex": "no"
            }
        },
        {
            "filename": "setup_quarto_prerelease.sh",
            "config": {
                "r": False,
                "quarto": "prerelease",
                "tex": "no"
            }
        },
        {
            "filename": "setup_r_only.sh",
            "config": {
                "r": True,
                "air": True,
                "quarto": "no",
                "tex": "no"
            }
        },
        {
            "filename": "setup_r_quarto_tex.sh",
            "config": {
                "r": True,
                "air": True,
                "quarto": "prerelease",
                "tex": "apt",
                "tex_packages": ["pandoc", "texlive-latex-extra", "texlive-luatex", "texlive-science"]
            }
        },
        {
            "filename": "setup_r_tex_full.sh",
            "config": {
                "r": True,
                "air": True,
                "quarto": "prerelease",
                "tex": "apt",
                "tex_packages": ["pandoc", "texlive-full"]
            }
        }
    ]

    print(f"Generating scripts for Ubuntu '{args.distro}'...")

    for item in configs:
        fname = item["filename"]
        cfg = item["config"]
        # Apply distro override
        cfg["distro_codename"] = args.distro
        
        content = generate_script_content(cfg)
        
        out_path = os.path.join(args.output_dir, fname)
        with open(out_path, "w") as f:
            f.write(content)
        
        # Make executable
        os.chmod(out_path, 0o755)
        print(f"Generated: {out_path}")

if __name__ == "__main__":
    main()
