#!/bin/bash
set -e

# Generated by github.com/jsperger/jules-r-tex-setup/generate_setup_scripts.py
# Target Distro: noble



# ========================= R installation =========================
# Installing R using r2u (https://github.com/eddelbuettel/r2u)
# Target script: add_cranapt_noble.sh
echo "Installing R for noble..."
curl -f https://raw.githubusercontent.com/eddelbuettel/r2u/refs/heads/master/inst/scripts/add_cranapt_noble.sh | sudo bash



# ======================= Air installation =========================
echo "Installing Posit Air..."
curl -LsSf https://github.com/posit-dev/air/releases/latest/download/air-installer.sh | sudo AIR_INSTALL_DIR=/usr/local/bin sh



# ========================= Verification =========================
echo "Verifying installation..."
R --version
air --version
echo "Setup complete!"
