#!/bin/bash
set -e

# Generated by github.com/jsperger/jules-r-tex-setup/generate_setup_scripts.py
# Target Distro: noble



# ========================= R installation =========================
# Installing R using r2u (https://github.com/eddelbuettel/r2u)
# Target script: add_cranapt_noble.sh
echo "Installing R for noble..."
curl -f https://raw.githubusercontent.com/eddelbuettel/r2u/refs/heads/master/inst/scripts/add_cranapt_noble.sh | sudo bash



# ======================= Air installation =========================
echo "Installing Posit Air..."
curl -LsSf https://github.com/posit-dev/air/releases/latest/download/air-installer.sh | sudo AIR_INSTALL_DIR=/usr/local/bin sh



# ======================= Quarto installation (Prerelease) ======================
REPO="quarto-dev/quarto-cli"
ARCH_PATTERN="linux-amd64.deb"

echo "Finding latest Quarto prerelease..."
# Fetch releases list and take the first one (which is the absolute latest, usually prerelease)
DOWNLOAD_URL=$(curl -s https://api.github.com/repos/$REPO/releases |     jq -r '.[0].assets[] | select(.name | endswith("'"$ARCH_PATTERN"'")) | .browser_download_url')

if [ -z "$DOWNLOAD_URL" ] || [ "$DOWNLOAD_URL" == "null" ]; then
    echo "Error: Could not find the latest .deb asset for $ARCH_PATTERN."
    exit 1
fi

FILE_NAME=$(basename "$DOWNLOAD_URL")
echo "Downloading $FILE_NAME..."
curl -L -o "/tmp/$FILE_NAME" "$DOWNLOAD_URL"

echo "Installing Quarto..."
sudo apt update
sudo apt install -y "/tmp/$FILE_NAME"
rm "/tmp/$FILE_NAME"



# ========================= TeX installation (Apt) =========================
echo "Installing TeX Live packages: pandoc texlive-full..."
sudo apt update
sudo apt install -y pandoc texlive-full



# ========================= Verification =========================
echo "Verifying installation..."
R --version
air --version
quarto --version
echo "Setup complete!"
