#!/bin/bash
set -e

# Generated by github.com/jsperger/jules-r-tex-setup/generate_setup_scripts.py
# Target Distro: noble



# ======================= Quarto installation (Latest Stable) ======================
REPO="quarto-dev/quarto-cli"
ARCH_PATTERN="linux-amd64.deb"

echo "Finding latest stable Quarto release..."
# The /releases/latest endpoint specifically excludes pre-releases
DOWNLOAD_URL=$(curl -s "https://api.github.com/repos/$REPO/releases/latest" |     jq -r '.assets[] | select(.name | endswith("'"$ARCH_PATTERN"'")) | .browser_download_url')

if [ -z "$DOWNLOAD_URL" ] || [ "$DOWNLOAD_URL" == "null" ]; then
    echo "Error: Could not find the stable .deb asset for $ARCH_PATTERN."
    exit 1
fi

FILE_NAME=$(basename "$DOWNLOAD_URL")
echo "Downloading $FILE_NAME..."
curl -L -o "/tmp/$FILE_NAME" "$DOWNLOAD_URL"

echo "Installing Quarto..."
sudo apt update
sudo apt install -y "/tmp/$FILE_NAME"
rm "/tmp/$FILE_NAME"



# ========================= Verification =========================
echo "Verifying installation..."
quarto --version
echo "Setup complete!"
